<?php
    /** @var \Apsis\One\Block\Cart $block */
    $items = $block->getCartItems();
?>
<?php if (! empty($items)): ?>
    <style type="text/css">
        @media screen and (max-width: 600px) {
            .ecom-img, .ecom-img img {
                width: 90px!important;
                height: auto!important;
            }
            .nomob {
                display: none!important;
            }
            .rsd, td.rsd img, th.rsd img, div.rsd img {
                width: 100%!important;
                height: auto!important;
            }
        }
    </style>

    <table style="width:600px;" border="0" cellpadding="0" cellspacing="0" bgcolor="#ffffff" class="rsd" align="center">
        <tr>
            <th style="padding:20px;">
                <table style="width:100%;" border="0" cellpadding="0" cellspacing="0" bgcolor="#ffffff">
                    <tr>
                        <th></th>
                        <th align="left" style="padding-left:15px; font:14px/1.2 Georgia, Times, Times New Roman, serif; color: #717171; font-weight: normal;">
                            <?= __("Product details") ?>
                        </th>
                        <th class="nomob" align="right" style="font:14px/1.2 Georgia, Times, Times New Roman, serif; color: #717171; font-weight: normal;">
                            <?= __("Quantity") ?>
                        </th>
                        <th align="right" style="font:14px/1.2 Georgia, Times, Times New Roman, serif; color: #717171; font-weight: normal; padding-left:15px;">
                            <?= __("Price") ?>
                        </th>
                    </tr>
                    <tr>
                        <th colspan="4" style="line-height:1px;" height="7">
                            <img src="http://static.anpdm.com/shared/images/pixel.gif" width="1" height="7" style="display:block;" />
                        </th>
                    </tr>
                    <tr>
                        <th colspan="4" style="line-height:1px;" height="1" bgcolor="#dddddd">
                            <img src="http://static.anpdm.com/shared/images/pixel.gif" width="1" height="1" style="display:block;" />
                        </th>
                    </tr>
                    <tr>
                        <th colspan="4" style="line-height:1px;" height="15">
                            <img src="http://static.anpdm.com/shared/images/pixel.gif" width="1" height="15" style="display:block;" />
                        </th>
                    </tr>

                    <!-- repeating module -->
                    <?php foreach ($items as $item): ?>
                        <tr>
                            <th width="130" class="ecom-img">
                                <a href=<?= $block->escapeUrl($item->product_url) ?>>
                                    <img src=<?= $block->escapeHtml($item->product_image_url) ?> width="130" border="0" style="display:block;"/>
                                </a>
                            </th>
                            <th align="left" style="padding-left:15px; font:14px/1.2 Arial, Helvetica, sans-serif; color: #333333;">
                                <div style="font:16px/1.2 Georgia, Times, Times New Roman, serif;font-weight:normal; text-transform:uppercase; color:#333333!important;">
                                    <a href=<?= $block->escapeUrl($item->product_url) ?> style="color:#333333; text-decoration:none;">
                                        <?= $block->escapeHtml($item->name) ?>
                                        <?php if (! empty($item->product_options)): ?>
                                            <div style="color:#717171; text-decoration:none; font-size: 12px;">
                                                <?php foreach ($item->product_options as $product_option): ?>
                                                    <?php $option = $product_option->option_value ?>
                                                    <div>
                                                        <?php if (! empty($option->value)): ?>
                                                            <?= $option->title . ' : ' . $option->value ?>
                                                        <?php else: ?>
                                                            <?= $option->title . '<span style="text-transform:none!important;"> x </span> ' . $option->qty?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                        <?php endif; ?>
                                    </a>
                                </div>
                            </th>
                            <th align="right" style="padding-left:15px; font:14px/1.2 Arial, Helvetica, sans-serif; color: #333333;" class="nomob">
                                <div style="font-weight:normal;">
                                    <?= $block->escapeHtml($item->qty_ordered) ?>
                                </div>
                                <div> &nbsp; </div>
                            </th>
                            <th align="right" style="padding-left:15px; font:14px/1.2 Arial, Helvetica, sans-serif; color: #333333; white-space:nowrap;">
                                <div style="font-weight:normal; white-space:nowrap;">
                                    <?= $block->escapeHtml($block->getCurrencyByStore($item->price_amount)) ?>
                                </div>
                                <div> &nbsp; </div>
                            </th>
                        </tr>
                        <tr>
                            <th colspan="4" style="line-height:1px;" height="15">
                                <img src="http://static.anpdm.com/shared/images/pixel.gif" width="1" height="15" style="display:block;" />
                            </th>
                        </tr>
                    <?php endforeach; ?>
                    <!-- repeating module -->

                    <tr>
                        <th colspan="4" style="line-height:1px;" height="1" bgcolor="#dddddd">
                            <img src="http://static.anpdm.com/shared/images/pixel.gif" width="1" height="1" style="display:block;" />
                        </th>
                    </tr>
                    <tr>
                        <th align="right" colspan="4" style="padding: 10px 0 15px;">
                            <table border="0" cellpadding="0" cellspacing="0" bgcolor="#9fb4cf" style="border-radius: 5px;">
                                <tr>
                                    <th style="font:14px/1.2 Arial, Helvetica, sans-serif; color:#ffffff; font-weight:bold; padding:10px 20px;">
                                        <span style="color:#ffffff !important;">
                                            <a href=<?= $block->escapeUrl($block->getUrlForCheckoutLink()) ?> style="color:#ffffff; text-decoration:none;"><?= __("CHECKOUT") ?></a>
                                        </span>
                                    </th>
                                </tr>
                            </table>
                        </th>
                    </tr>
                </table>
            </th>
        </tr>
    </table>
<?php endif; ?>