<?php
/** @var \Apsis\One\Block\Customer\Subscription $block */
?>
<form id="apsis-subscription-form-validate"
        method="post"
        action="<?= $block->escapeHtml($block->getSaveUrl()) ?>">
    <?= $block->getBlockHtml('formkey') ?>
    <legend class="legend">
        <span>
            <?= $block->escapeHtml(__('General Subscription')) ?>
        </span>
    </legend>
    <fieldset class="fieldset">
        <div class="field choice">
            <input type="checkbox"
                   id="subscription"
                   name="is_subscribed"
                   value="1"
                   title="<?= $block->escapeHtmlAttr(__('General Subscription')) ?>"
                   checked="checked"
                   class="checkbox">
            <label for="subscription" class="label">
                <span>
                    <?= $block->escapeHtml(__('General Subscription')) ?>
                </span>
            </label>
        </div>
        <?= $block->getChildHtml('customer.form.newsletter.extra') ?>
    </fieldset>
    <?php if (! empty($sortedTopicArr = $block->getConsentListTopicsToShow())) : ?>
        <fieldset class="fieldset">
            <legend class="legend">
                <span>
                    <?= $block->escapeHtml(__('Topic Subscription')) ?>
                </span>
            </legend>
            <ul class="form-list" style="padding-left: 0">
                <?php foreach ($sortedTopicArr as $list) : ?>
                        <h5 style="margin-bottom: 10px">
                            <?= $block->escapeHtml($list['name']) ?>
                        </h5>
                        <?php foreach ($list['topics'] as $topic) : ?>
                            <li class="control" style="display: block; margin: 5px 0 5px 10px">
                                <input type="checkbox"
                                       name="topic_subscriptions[]"
                                       id="<?= $block->escapeHtml($topic["value"]); ?>"
                                       value="<?= $block->escapeHtml($topic["value"]) ?>"
                                       title="<?= $block->escapeHtml($topic["name"]) ?>"
                                    <?php if ($topic["consent"]) : ?>
                                        checked="checked"
                                    <?php endif; ?> class="checkbox"
                                />
                                <label for="<?= $block->escapeHtml($topic["value"]); ?>">
                                    <?= $block->escapeHtml($topic["name"]) ?>
                                </label>
                            </li>
                        <?php endforeach; ?>
                <?php endforeach; ?>
            </ul>
        </fieldset>
    <?php endif; ?>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Save" class="action save primary">
                <span>Save</span>
            </button>
        </div>
    </div>
</form>