<?php  /** @var \Apsis\One\Block\Adminhtml\Block $block */ ?>
<script type="text/x-magento-init">
{
    "*": {
        "Apsis_One/js/config":{
            "isSectionAlreadyMapped":"<?= $block->isSectionAlreadyMapped() ?>",
            "isAccountAlreadyConfigured":"<?= $block->isAccountAlreadyConfigured() ?>",
            "isProfileDeleteEnabled":"<?= $block->isProfileDeleteEnabled() ?>",
            "getResetUrl":"<?= $block->getResetUrl() ?>"
        }
    }
}
</script>
