<?php /** @var \Magento\Backend\Block\Template $block */ ?>
<div class="apsis-config-info-container">
    <img alt="apsisLogo" src="<?= $block->getViewFileUrl('Apsis_One::images/logo.png'); ?>"/>
    <strong class="apsis-config-info-heading">APSIS One Integration</strong>
    <span>
        Please select a <strong>Store View</strong> from config <strong>Scope</strong> dropdown to configure integration.
        Visit <a href="https://help.apsis.one/en/" target="_blank">Apsis One help center</a> for further setup guide and support documentation.
    </span>
    <img alt="apsisLogo" src="<?= $block->getViewFileUrl('Apsis_One::images/tip.png'); ?>"/>
</div>
