<?php /** @var \Magento\Backend\Block\Template $block */ ?>
<div style="padding: 2rem 0; margin-left: 4rem;">
    <img style="display: block; margin-bottom: 1rem;" alt="apsisLogo" src="<?= $block->getViewFileUrl('Apsis_One::images/logo.png'); ?>"/>
    <strong style="display: block; font-size: 1.7rem; font-weight: 700; margin-bottom: 1rem;">APSIS One Integration</strong>
    <span style="display: block; margin-bottom: 2rem;">
        Please select a <strong>Store View</strong> from config <strong>Scope</strong> dropdown to configure integration.
        Visit <a href="https://help.apsis.one/en/" target="_blank">Apsis One help center</a> for further setup guide and support documentation.
    </span>
    <img style="display: block; margin-bottom: 1rem;" alt="apsisLogo" src="<?= $block->getViewFileUrl('Apsis_One::images/tip.png'); ?>"/>
</div>
