<?php /** @var \Apsis\One\Block\Adminhtml\LogViewerBlock $block */?>
<div style="border: 4px solid #dfdfdf; overflow: hidden; height: 510px; padding: 5px;">
    <pre id="log_data" style="width:100%; height:500px; overflow:auto; margin:0; padding:3px; background:black;
    color:#2EC029; font:normal 11px Lucida Console, Courier New, serif; line-height:1.6;">
        <?= $block->getFileContent(); ?>
    </pre>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Apsis_One/js/logger" : {}
        }
    }
</script>
